FROM allenwei/ruby-1.9.2

WORKDIR /usr/src/app

RUN curl -LO https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer
RUN bash rvm-installer
RUN apt-get install build-essential

RUN rvm pkg install zlib
RUN rvm pkg install openssl
RUN rvm pkg install iconv

RUN export rvm_path=/usr/local/rvm 
RUN rvm install 1.9.2 -C --with-zlib-dir=$rvm_path/usr,--with-openssl-dir=$rvm_path/usr,--with-iconv-dir=$rvm_path/usr
RUN rvm rubygems latest
RUN rvm use 1.9.2 --default
RUN rvm reload
RUN gem install bundler

# for pygments
RUN apt-get install python python-dev

RUN jekyll --server
